name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Granting private modules access
      run: |
        git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/onflow".insteadOf "https://github.com/onflow"
    - uses: actions/checkout@v2
    - name: Build relic
      run: make clean-relic && make crypto/relic/build
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
  test:
    name: Unit Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Run CI
      run: make ci
  golangci:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29
        args: -v --build-tags relic
