name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: docker run -v $PWD:/go/flow -w "/go/flow" "gcr.io/flow-container-registry/golang-cmake:v0.0.7" make ci
